// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users.proto

// Protobuf Java Version: 3.25.1
package com.rlgino.CardsService.infrastructure.usersproto;

public final class Users {
  private Users() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_usersproto_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_usersproto_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_usersproto_SearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_usersproto_SearchRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013users.proto\022\nusersproto\"u\n\004User\022\n\n\002id\030" +
      "\001 \001(\t\022\014\n\004name\030\002 \001(\t\022+\n\006status\030\003 \001(\0162\033.us" +
      "ersproto.User.ItemStatus\"&\n\nItemStatus\022\014" +
      "\n\010INACTIVE\020\000\022\n\n\006ACTIVE\020\001\"\035\n\rSearchReques" +
      "t\022\014\n\004user\030\001 \001(\t2H\n\013UserService\0229\n\nSearch" +
      "User\022\031.usersproto.SearchRequest\032\020.usersp" +
      "roto.UserBL\n1com.rlgino.CardsService.inf" +
      "rastructure.usersprotoP\001Z\025grpcServer/use" +
      "rsprotob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_usersproto_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_usersproto_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_usersproto_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Status", });
    internal_static_usersproto_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_usersproto_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_usersproto_SearchRequest_descriptor,
        new java.lang.String[] { "User", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
